version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - ollama
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
volumes:
  ollama_models:
